#!/bin/sh

shopt -q extglob

home="$(df -h | grep /home | awk '{print $4 "/" $2}' | tr '\n' ' ')"
var="$(df -h | grep /var$ | awk '{print $4 "/" $2}' | tr '\n' ' ')"
icon="💾"

printf "/var: %s /home: %s" "$var$icon" "$home$icon"
