#!/bin/sh

# File preview handler for lf.

set -C -f
IFS="$(printf '%b_' '\n')"; IFS="${IFS%_}"

image() {
	if [ -n "$DISPLAY" ] && [ -z "$WAYLAND_DISPLAY" ] && command -V ueberzug >/dev/null 2>&1; then
		printf '{"action": "add", "identifier": "PREVIEW", "x": "%s", "y": "%s", "width": "%s", "height": "%s", "scaler": "contain", "path": "%s"}\n' "$4" "$5" "$(($2-1))" "$(($3-1))" "$1" > "$FIFO_UEBERZUG"
	else
		mediainfo "$1"
	fi
}

ifub() {
	[ -n "$DISPLAY" ] && [ -z "$WAYLAND_DISPLAY" ] && command -V ueberzug >/dev/null 2>&1
}

case "$(file --dereference --brief --mime-type -- "$1")" in
	image/*) image "$1" "$2" "$3" "$4" "$5" ;;
	text/html) lynx -width="$4" -display_charset=utf-8 -dump "$1"  ;;
	text/troff) man ./ "$1" | col -b ;;
	text/* | */xml | application/json) bat --terminal-width "$4" -f "$1" ;;
	application/zip) atool -l -- "$1" ;;
        application/x-tar | application/gzip | application/bzip) atool -l -- "$1" | \
            awk '{printf ("%12s kB  %9s  %5s  %s\n", $3, $4, $5, $6);}' | sort -rn ;;
        application/x-lzh-compressed) lha -l "$1" | tail -n+3 | awk '{printf("%3s %2s %5s %s\n", $4, $5, $6, $7);}' ;;
        application/x-7z-compressed) atool -l -- "$1" | tail -n+21 | head -n-2 | \
            awk '{printf ("%12s kB  %9s  %5s  %1s\n", $4, $1, $2, $5);}' | sort -rn ;;
        
        audio/* | application/octet-stream) mediainfo "$1" || exit 1 ;;
        application/x-amiga-disk-format) xdftool "$1" list || exit 1 ;;
        video/webm) mediainfo "$1" || exit 1 ;;
	video/* )
		CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}')"
		[ ! -f "$CACHE" ] && ffmpegthumbnailer -i "$1" -o "$CACHE" -s 0
		image "$CACHE" "$2" "$3" "$4" "$5"
		;;
        */pdf)
		CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}')"
		[ ! -f "$CACHE.jpg" ] && pdftoppm -jpeg -f 1 -singlefile "$1" "$CACHE"
		image "$CACHE.jpg" "$2" "$3" "$4" "$5"
		;;
        *opendocument*) odt2txt "$1" ;;
	application/pgp-encrypted) gpg -d -- "$1" ;;
esac
exit 1
